BaseDir:=../
cmd:=\
  ctags -R *

.PHONY:main
main:
	$(cmd); cd makeout; make clean; make

name:=./run/repsoftmax_app.sh
name:=./run/rbm_roc.sh
name:=./run/tbm_app.sh
name:=./run/rbm_unittest.sh
name:=./run/hrbm_app.sh
name:=./run/ali_app.sh
name:=./run/crbm_app.sh
name:=./run/bmmatrix_app.sh
name:=./run/rbm_app.sh
.PHONY:run
run:
	$(name)
